# site properties and page defaults
title:  DNSLab @ Inha Univ.
subtitle: Distributed and Networked Systems Lab.
description: Distributed and Networked Systems Lab. (DNSLab) of the Department of Computer Engineering, Inha University located in the Incheon Metropolitan City, Republic of Korea is established by [Prof. Heejun Roh](https://www.hjroh.kr) on March 1, 2024. Currently, our research activities include (1) Network Telemetry including network traffic monitoring and classification, (2) Radio Frequency (RF)-powered computing and networking systems, (3) RF sensing and wireless coexistence, and (4) design, implementation, and analysis of various network protocols and networked systems.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: hjroh@inha.ac.kr
  orcid: 0000-0002-6432-3234
  google-scholar: AjUYnyIAAAAJ
  github: dnslab-inha
  twitter: dnslab-inha
  youtube: dnslab-inha

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
  - flexible_include

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
