# 2024
- id: doi:10.3745/PKIPS.y2024m05a.114
- id: doi:10.1016/j.icte.2023.12.008
- title: Feasibility of Adopting Multipath TCP to BitTorrent-based Applications with Mininet
  authors:
    - Byeonghyeon Jeon
    - Heejun Roh
    - Seunghye Paik
    - Wonjun Lee
  publisher: Proceedings of the 2024 KICS Summer Conference
  date: 2024-06-19
  link: https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE11906454
- title: Evaluating SPLT-based and nPrint-based AutoML Classifiers on an Encrypted Application Traffic over VPN Dataset
  authors:
    - Byeonghyeon Jeon
    - Eunhang Kim
    - Jihwan Oh
    - Heejun Roh
  publisher: Proceedings of the  Korea Software Congress 2024 (KSC 2024)
  date: 2024-12-18
  link: \#

# 2023
- id: doi:10.13089/JKIISC.2023.33.2.267
- title: A Survey of Sequential Feature Representation Techniques in Encrypted Network Traffic Analysis
  authors:
    - Geunho Kim
    - Joonseo Ha
    - Heejun Roh
  publisher: Proceedings of the KIISE Korea Software Congress 2023 (KSC 2023)
  date: 2023-12-20
  link: https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE11705631
- title: Reproducibility Analysis of Linux 802.11n CSI Tool-based Wireless Network Experiments through AoA/AoD Estimation
  authors:
    - Geunho Kim
    - Sangbin Kim
    - Joonseo Ha
    - Heejun Roh
  publisher: Proceedings of the KIISE Korea Computer Congress 2023 (KCC 2023)
  date: 2023-06-17
  link: https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE11488589
- title: On the Effectiveness of nPrint to an Encrypted Malware Traffic Dataset
  authors:
    - Jaewoo Park
    - Minsoo Kim
    - Heejun Roh
  publisher: Proceedings of the KIISE Korea Computer Congress 2023 (KCC 2023)
  date: 2023-06-17
  link: https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE11488588
- title: A Survey on Traffic Data Preprocessing for Encrypted Traffic Analysis Based on Machine Learning
  authors:
    - Dohyun Ahn
    - Minki Hong
    - Joonseo Ha
    - Heejun Roh
  publisher: Proceedings of the KIISC Conference on Information Security and Cryptography Summer 2023 (CISC-S 2023)
  date: 2023-06-22
  link: \#
- title: A Survey on Website Fingerprinting Techniques Based on Machine Learning
  authors:
    - Joonseo Ha
    - Heejun Roh
  publisher: Proceedings of the 2023 Korea institute of Information Security and Cryptology Choongchung Chapter Conference (KIISC CC 2023)
  date: 2023-06-22
  link: \#

# 2022
- id: doi:10.1109/ICTC55196.2022.9952872
- id: doi:10.1109/ACCESS.2022.3201648
- title: Impact of Destination Context of TLS-Encrypted Traffic in Malware Family Classification
  authors:
    - Joonseo Ha
    - Heejun Roh
  publisher: Proceedings of the 32nd Joint Conference on Communications and Information (JCCI 2022)
  date: 2022-04-27
  link: \#
- title: Trends in Machine Learning Models for Encrypted Traffic Classification
  authors:
    - Doehyun Kim
    - Dohyun Ahn
    - Heejun Roh
  publisher: Proceedings of the 2022 Korea institute of Information Security and Cryptology Choongchung Chapter Conference (KIISC CC 2022)
  date: 2022-10-14
  link: \#

# 2021
- id: doi:10.3390/electronics10243180
- id: doi:10.3390/app12010155
- id: doi:10.3390/en14040928
- id: doi:10.1109/LCOMM.2020.3038255
- id: doi:10.1109/tmc.2019.2955080
- id: doi:10.1109/ICOIN50884.2021.9333996
- title: A Survey on TLS Fingerprinting for Cyber Threat Intelligence
  authors:
    - Heejun Roh
  publisher: The Korea Institute of Information Security and Cryptology
  date: 2021-10-30
  link: https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE10619258


# 2020
- id: doi:10.1109/JIOT.2020.2972915
- id: doi:10.1109/TNET.2020.2989387
- id: doi:10.1109/ICNP49622.2020.9259387
- id: doi:10.1109/INFOCOMWKSHPS50562.2020.9162971
- id: doi:10.1109/INFOCOMWKSHPS50562.2020.9162658

# 2019
- id: doi:10.1109/access.2019.2957434

# 2018
- id: doi:10.1016/j.jnca.2018.08.011
- id: doi:10.1109/LWC.2018.2863294

# 2017
- id: doi:10.1109/ACCESS.2017.2755638
- id: doi:10.1109/LCOMM.2017.2676773
- id: doi:10.1016/j.jnca.2016.12.006
- id: doi:10.1109/MVT.2016.2604409
- id: doi:10.1007/978-3-319-60717-7_14

# 2016
- id: doi:10.1109/TCE.2016.7514670

# 2015
- id: doi:10.1109/ICTC.2015.7354607
- id: doi:10.1109/INFCOMW.2015.7179338

# 2014
- id: doi:10.1109/LCOMM.2013.112613.132085

# 2013
- id: doi:10.1002/wcm.1128
  date: 2013-05-01
- id: doi:10.1109/ICCNC.2013.6504211
- id: doi:10.1109/INFCOM.2013.6566947

# 2012
- id: doi:10.1587/transcom.E95.B.2956
- id: doi:10.1155/2012/156590
- id: doi:10.1109/JSAC.2012.121022

# 2011
- id: doi:10.1145/2079327.2079335

# 2010
- id: doi:10.1587/transcom.E93.B.1029
- id: doi:10.1145/1923641.1923651
- id: doi:10.1109/INFCOM.2010.5462126
- id: doi:10.1007/978-3-642-14654-1_21



